<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 10:47 AM
 */
use Application\Info;
/** @var \Application\Model\QuestionType $questionType */
?>


<div id="main-window-for-question-creation">

</div>
<!--<div class="col-lg-4"></div>-->
<!--<div class="col-lg-4">-->
<!--    <form method='POST' action="/questions/questions/create" >-->
<!--        <div class="form-group row --><?php //echo isset($error)?'has-danger':''; ?><!--">-->
<!--            <label for="name" class="col-2 col-from-label">Enter the Name of the Question:</label>-->
<!--            <div class="col-10">-->
<!--                <input readonly onfocus="this.removeAttribute('readonly');" name='name' id="name" class="form-control " type="text" placeholder="Name of question">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group row --><?php //echo isset($error)?'has-danger':''; ?><!--">-->
<!--            <label for="questionType" class="col-2 col-from-label">Pick the Question Type:</label>-->
<!--            <div class="col-10">-->
<!--                <a href='/questions/question-types' class='btn btn-primary '>Go To Question Types</a>-->
<!--                <select id="questionType" name="QuestionTypeID" class="form-control">-->
<!--                    --><?php
//                    foreach(Info::QuestionTypesTable()->fetch() as $questionType){
//                        echo "<option value='{$questionType->getQuestionTypeID()}'>{$questionType->getName()}</option>";
//                    }
//                    ?>
<!--                </select>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div  class="btn btn-primary copyFromID">Copy From</div>-->
<!--        <div class="copyFromIndicator">-->
<!--            <span class="copyFromText"></span>-->
<!--            <span class="copyFromDelete"></span>-->
<!--        </div>-->
<!--        <input type="hidden" name="copyFrom"/>-->
<!---->
<!---->
<!--        <div class="form-group row login-form-submit-container">-->
<!--            <input class="btn btn-default form-control" type="submit" value="Create"/>-->
<!--        </div>-->
<!--        --><?php
//        if(isset($error)){
//           echo "<h4 class='text-danger'>error</h4>";
//        }
//        ?>
<!--    </form>-->
<!--</div>-->
<script>
$(document).ready(function (){
    Components.QuestionTypes().appendTo($("#main-window-for-question-creation"));


})
</script>

