<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 3:40 PM
 */
use Application\Info;

/** @var \Application\Model\Question $question */
$questionType=$question->getQuestionType();
$questionTypeUrl='http://'.$_SERVER['HTTP_HOST']."/questions/question-types/{$questionType->getQuestionTypeID()}";
$questionRunnerUrl='http://'.$_SERVER['HTTP_HOST']."/questions/questions/{$question->getQuestionID()}/run";
$questionRunnerEditor='http://'.$_SERVER['HTTP_HOST']."/questions/questions/{$question->getQuestionID()}/editor";
?>

<div class="col-lg-12">
    <!-- <span url='<?php  echo $questionRunnerEditor; ?>' name='Question Editor' class="editorBtn btn btn-default">Open Question Editor</span> -->
    <!-- <span url='<?php  echo $questionTypeUrl; ?>' name='Question Type Editor' class="editorBtn btn btn-default">Open Question Type Editor</span> -->
    <a target="_blank" href='<?php  echo $questionRunnerEditor; ?>' name='Question Editor' class=" btn btn-default">Open Question Editor</a>
    <a target="_blank" href='<?php  echo $questionTypeUrl; ?>' name='Question Type Editor' class=" btn btn-default">Open Question Type Editor</a>
</div>
<?php
echo $viewable;
?>
<!-- <iframe id='runningQ' style="width:100vw;height:100vh" src="<?php echo $questionRunnerUrl  ?>"></iframe> -->


<script>
    var $_ThisURL='<?php  echo "http://uh-celo.local".Info::Url() ?>';
    var $_MainEvents=new EventHandler();
    var $_Windows={};
    $_Windows[$_ThisURL]=window;
    /***********************************************************************/

    var $questionTypeUrl='<?php  echo $questionTypeUrl; ?>';
    var $questionRunnerUrl='<?php  echo $questionRunnerUrl; ?>';
    var $questionRunnerEditor='<?php  echo $questionRunnerEditor; ?>';

    $_MainEvents.on("windowmessage",function(event)
    {
        //If its a save
        for(var url in $_Windows){
            if(url==event.data.url || $_ThisURL==url){
                continue;
            }

            $_Windows[url].location.reload(true);
        }

        if($_ThisURL!=event.data.url)
        {
            document.getElementById('runningQ').contentWindow.location.reload(true);
        }
    });

    $_MainEvents.on("windowhasopened",function(event)
    {
        $_Windows[event.url]=window.open(event.url,event.name, "width=200,height=100");
        setTimeout(function(){
            $_Windows[event.url].myOpener=window
        },5000);

    });

    /***********************************************************************/
    $(".editorBtn").click(function(){
        var url=$(this).attr("url");
        var name=$(this).attr("name");
        $_MainEvents.trigger("windowhasopened",{url:url,name:name});
    });

    /***********************************************************************/
    window.addEventListener('message', function(event)
    {
        var $url=event.data.url;
        if(!$url){
            return;
        }

        $_MainEvents.trigger('windowmessage',event);


    }, false);







</script>