<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 10:57 AM
 */
use Application\Info;

/** @var \Application\Model\Question  $question */



?>

<div class="well col-lg-12">

    <div class="col-lg-9">
        <h4>Tags</h4>
        <span class="tag-action" tag-category="Question" tag-refid="<?php echo $question->getQuestionID() ?>"></span>
    </div>
    <div class="col-lg-3">
        <div class="pull-right">
            <form action="/questions/questions/create" method="post">
                <input type="hidden" name="copyFrom" value="<?php  echo $question->getQuestionID() ?>">
                <input type="submit" class="btn btn-warning" value="Copy This Question">
            </form>
        </div>
    </div>
</div>


<div class="col-lg-12">
    <span style='display:none' class="loadingSpinner spinner"></span>
    <a  style='' class="quickStatus text-success"></a>
</div>
<div class="col-lg-12" id="mainContent">
</div>

<script>
    var $_ThisURL='<?php  echo "http://uh-celo.local".Info::Url() ?>';
    var $baseUrl="<?php echo \Application\Info::Url();  ?>";
    var $_events=new EventHandler();

    /***********************************************************************/
    /* Internet Code                                                       */
    /***********************************************************************/
    function QuestionWidget(){
        this.$_cleanedData={};
        this._managed_data={};
        this._element=$("#mainContent");

    }

    $.extend(QuestionWidget.prototype, {

        load:function(callback)
        {
            var $this=this;
            $.get($baseUrl+"/load",function(data){
                $this._managed_data=data;
                callback?callback():true;
            });
        },
        setAnswer:function(answer){
            this._managed_data["answer"]=answer;
            $_events.trigger("save");
        },
        getAnswer:function(){
            return this._managed_data["answer"];
        },
        save:function(callback)
        {
            var $this=this;
            //this.beforeSubmitingChanges(this.$_cleanedData["parameters"]);
            $.ajax({
                url:$baseUrl+"/save",
                method:"POST",
                data: JSON.stringify({ "parameters": $this.$_cleanedData,
                                       "answer":$this._managed_data["answer"]}),
                success:function(data) {
                    //$this.afterSubmitingChanges(data);
                    callback?callback():true;
                }
            });

        },
        refresh:function(callback)
        {

            var $this=this;
            $this._element.empty();
            this.load(function(){
                $this.$_cleanedData=$this.setup($this._managed_data["parameters"]);
                $this.render($this._element);

                callback?callback():true;
            });
        }
    });


    /***********************************************************************/
    /***********************************************************************/
    /*                      Custom Javascript Code                         */
    /***********************************************************************/
    /***********************************************************************/
    <?php
    echo $question->getQuestionTypeManager()->getDevelopmentCode();
    ?>
    /***********************************************************************/


    /***********************************************************************/
    /* Internet Code                                                       */
    /***********************************************************************/
    var mainWidget=new QuestionWidget();
    $_events.on("load",function(){
        $_events.trigger("loading","started");
        var $this=$(this);
        mainWidget.refresh(function(){
            $_events.trigger("loading","ended");
            setTimeout(function(){
                //$_events.trigger("idle");
            },2000);
        });
    });

    $_events.on("loading","started",function(){
        $(".quickStatus").text("Loading...");
        $_events.trigger("spinner","started");
    });

    $_events.on("loading","ended",function(){
        $(".quickStatus").text("Loaded!");
        $_events.trigger("spinner","ended");
    });

    $_events.on("idle",function() {
        $(".quickStatus").text("");
        $_events.trigger("spinner","ended");
    });

    $_events.on("save",function(){
        $_events.trigger("saving","started");
        var $this=$(this);
        mainWidget.save(function(){
            $_events.trigger("saving","ended");
            setTimeout(function(){
                //$_events.trigger("idle");
            },2000);
        });
    });

    $_events.on("saving","started",function(){
        $(".quickStatus").text("Saving...");
        $_events.trigger("spinner","started");
    });

    $_events.on("saving","ended",function(){
        $(".quickStatus").text("Saved!");
        $_events.trigger("spinner","ended");
        //window.myOpener.postMessage({url:$_ThisURL,name:'Question Editor',message: 'saved',type:'questionEditor'}, '<?php  echo "http://uh-celo.local".Info::Url() ?>');
    });

    $_events.on("spinner","started",function(){
        $(".loadingSpinner").css({"display":""});
    });

    $_events.on("spinner","ended",function(){
        $(".loadingSpinner").css({"display":"none"});
    });
    window.addEventListener('message', function(event) {
        window.location.reload(true);

    }, false);
    $(window).bind('keydown', function(event) {
        if (event.ctrlKey || event.metaKey) {
            switch (String.fromCharCode(event.which).toLowerCase()) {
                case 's':
                    event.preventDefault();
                    $_events.trigger("save");
                    break;
                case 'l':
                    event.preventDefault();
                    $_events.trigger("load");
                    break;
            }
        }
    });

    $(document).ready(function(){
        $(this).data("events",$_events);
        $_events.trigger("load");
    });

</script>
