<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 5:43 AM
 */
/** @var \Application\Model\Question[] $questions */

use Application\Info;
use Application\Model\Question;

echo "<h2>Questions <b>(".count($questions).")</b> - <a href='/questions/questions/create' class='btn btn-primary'>Add</a></h2>"
?>

<table class="table questions-table">
    <thead>
    <tr>
        <th>Question</th>
        <th>Type</th>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach($questions as $question)
    {
        $question=(new Question())->exchangeArray($question);
        $url=Info::Url()."/".$question->getQuestionID();
        echo "<tr questionID='{$question->getQuestionID()}'>".
            "    <td>{$question->getQuestion()}</td>".
            "    <td>{$question->getQuestionType()->getName()}</td>".
            "</tr>";
    }
    ?>
    </tbody>
</table>

<script>
    Popups.Questions().Open();
</script>
