<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 10:57 AM
 */
use Application\Info;

/** @var \Application\Model\Question $question */

if(isset($this->question)){
    $question=$this->question;
}

if(!isset($this->answerURL)){
    $answerURL=$this->answerURL;
}
?>


<div class="col-lg-12" id="mainContent">
</div>
<div class="col-lg-12">
    <span style='display:none' class="loadingSpinner spinner"></span>
    <div  style='' class="quickStatus "></div>
</div>
<script>

    var baseUrl="<?php echo '/questions/questions/'.$question->getQuestionID().'/run'  ?>";

    var $_events=new EventHandler();

    /***********************************************************************/
    /* Internet Code                                                       */
    /***********************************************************************/
    function QuestionWidget(){
        this.$_cleanedData={};
        this._managed_data={};
        this._element=$("#mainContent");
    }

    $.extend(QuestionWidget.prototype, {

        load:function(callback)
        {
            var $this=this;
            $.get(baseUrl+"/load",function(data){
                $this._managed_data=data;
                callback?callback():true;
            });
        },
        setAnswer:function(answer){
            this._managed_data["answer"]=answer;
            $_events.trigger("test");
        },
        test:function(callback)
        {
            var $this=this;
            //this.beforeSubmitingChanges(this.$_cleanedData["parameters"]);
            $.ajax({
                <?php echo !isset($answerURL)?"url:baseUrl+\"/test\"":"url:'$answerURL'";  //Will Cause the Answer to be recorded    ?>,
                method:"POST",
                data: JSON.stringify({
                    <?php echo isset($answerURL)?"'sendAnswer':'$answerURL',":"";  //Will Cause the Answer to be recorded    ?>
                    "parameters": $this.$_cleanedData,
                    "answer":$this._managed_data["answer"],
                    "html":$this._element.html()}),
                 success:function(data) {
//                    if(!data.success){
//                        callback?callback('<h1 class="text-danger">Incorrect</h1>'+
//                                '<h4 class="text-warning">'+data.message+"</h4>"):true;
//
//                    }
//                    else
//                    {
                        callback?callback('<h1 class="text-success">Answered!</h1>'):true;
//                    }
                    //$this.afterSubmitingChanges(data);

                }
            });

        },
        refresh:function(callback)
        {
            var $this=this;
            $this._element.empty();
            this.load(function(){
                $this.$_cleanedData=$this.setup($this._managed_data["parameters"]);
                $this.render($this._element);

                callback?callback():true;
            });
        }
    });


    /***********************************************************************/
    /***********************************************************************/
    /*                      Custom Javascript Code                         */
    /***********************************************************************/
    /***********************************************************************/
    <?php
    echo $question->getQuestionTypeManager()->getDeploymentCode();
    ?>
    /***********************************************************************/


    /***********************************************************************/
    /* Internet Code                                                       */
    /***********************************************************************/
    var mainWidget=new QuestionWidget();
    $_events.on("load",function(){
        $_events.trigger("loading","started");
        var $this=$(this);
        mainWidget.refresh(function(){
            $_events.trigger("loading","ended");

        });
    });

    $_events.on("loading","started",function(){
        $(".quickStatus").html("Loading...");
        $_events.trigger("spinner","started");
    });

    $_events.on("loading","ended",function(){
        $(".quickStatus").html("Loaded!");
        $_events.trigger("spinner","ended");
    });

    $_events.on("idle",function() {
        $(".quickStatus").html("");
        $_events.trigger("spinner","ended");
    });

    $_events.on("test",function(){
        $_events.trigger("saving","started");
        var $this=$(this);
        mainWidget.test(function(message){
            $_events.trigger("saving","ended",{message:message});

        });
    });

    $_events.on("saving","started",function(){
        $(".quickStatus").text("Testing...");
        $_events.trigger("spinner","started");
    });

    $_events.on("saving","ended",function(e){
        $(".quickStatus").html(e.message);
        $_events.trigger("spinner","ended");
        //window.parent.postMessage({message: 'saved',type:'questionRunner'}, '<?php  echo "http://uh-celo.local".Info::Url() ?>');

    });

    $_events.on("spinner","started",function(){
        $(".loadingSpinner").css({"display":""});
    });

    $_events.on("spinner","ended",function(){
        $(".loadingSpinner").css({"display":"none"});
    });
    function windowMessage(event) {
        window.location.reload(true);

    }
    window.addEventListener('message', windowMessage, false);
    $(window).bind('keydown', function(event) {
        if (event.ctrlKey || event.metaKey) {
            switch (String.fromCharCode(event.which).toLowerCase()) {
                case 's':
                    event.preventDefault();
                    $_events.trigger("save");
                    break;
                case 'l':
                    event.preventDefault();
                    $_events.trigger("load");
                    break;
            }
        }
    });

    $(document).ready(function(){

        if(typeof $(this).data("events") !="undefined"){
            alert('Someone is here');
        }
        $(this).data("events",$_events);
        $_events.trigger("load");
        setTimeout(function(){

        },1000);

    });

</script>
