<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/2/2017
 * Time: 5:13 AM
 */

namespace Student\Controller;


use Application\Info;
use Application\Roles;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class UserController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {

        $navigation=new ViewModel();
        $navigation->setTemplate("layout/staff/navigation");


        $e->getViewModel()->addChild($navigation,"navigation");

        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub




        /*******************************************************************/
        return $parent;
    }
    public function indexAction()
    {
        $view=new ViewModel();
        $view->setTemplate('user/home');

        return $view;
    }
    public function logoutAction()
    {
        Info::LoginService()->SignOut();

        $this->redirect()->toRoute("student/login");

    }
    public function sectionHomeAction(){
        $view=new ViewModel();
        $view->setTemplate('user/section/home');
        $sectionID=$this->params()->fromRoute("sectionID");
        $section=Info::SectionTable()->getFromID($sectionID);
        if($section==null){
            return Info::getErrorView("Section unkown <span class='label label-primary'>$sectionID</span></h2>");
        }

        $contentID=$this->params()->fromRoute("contentID");
        if(!isset($contentID)){
            $contentID=$section->getMainCourseContentID();
        }
        $courseContent=Info::CourseContentTable()->getByID($contentID);
        $view->setVariable("contentItem",$courseContent);

        $view->setVariable("section",$section);
        return $view;
    }
}