<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(
    'view_manager' => array(
        'display_not_found_reason' => true,
        'display_exceptions'       => true,
        'doctype'                  => 'HTML5',
        'not_found_template'       => 'react/index',
        'exception_template'       => 'error/index',
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
        'strategies' => array(
            'ViewJsonStrategy',
        )
    ),
//
    'controllers' => array(
        'invokables' => array(
            'React\Controller\Index' => 'React\Controller\IndexController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes'=>array(
//            'react-home' => array(
//                'type' => 'segment',
//                'options' => array(
//                    'route'    => '/instructor/section/[:sectionid]',
//                    'defaults' => array(
//                        'controller' => 'React\Controller\Index',
//                        'action'     => 'index',
//                        'roles' => array(
//                            Roles::$ADMIN,
//                            Roles::$STUDENT,
//                            Roles::$TA,
//                            Roles::$INSTRUCTOR,
//                            Roles::$GUEST,
//                        ),
//                        'title'=>"React Home"
//                    ),
//                    'constraints'=>array(
//                        'sectionid'=>'[a-zA-Z0-9.\/]*'
//                    )
//
//                ),
//            )
        )
// Uncomment below to add routes
//        'routes' => array(
//            'react' => array(
//                'type' => 'Literal',
//                'options' => array(
//                    'route' => '/react',
//                    'defaults' => array(
//                        '__NAMESPACE__' => 'React\Controller',
//                        'controller' => 'React',
//                        'action' => 'index',
//                    )
//                )
//            )
//        ),
//        'may_terminate' => true,
//        'child_routes' => array(
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            )
//        )
    )
);