<?php
namespace Questions\Controller;
use Application\Info;
use Application\QuestionManager;
use Application\QuestionTypeManager;
use Slim\View;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 5:40 AM
 */
class QuestionTypeController  extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {

        /*******************************************************************/
        /* User Check                                                      */
        /*******************************************************************/
        Info::LoginService()->Authorize(array("Administrator","Instructor","Student","TA"));

        /*******************************************************************/
        $json=$e->getRouteMatch()->getParam("json");
        if(isset($json)){
            $e->getViewModel()->setTemplate("application/layout/empty");
        }


        $navigation=new ViewModel();
        $navigation->setTemplate("layout/staff/navigation");


        /*******************************************************************/
        $e->getViewModel()->addChild($navigation,"navigation");

        //e->getViewModel()->setTemplate("visitors/layout");
        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub


        /*******************************************************************/




        /*******************************************************************/
        return $parent;
    }


    /***********************************************************************/
    /* Helpers                                                             */
    /***********************************************************************/
    protected $_editorRoutePath="questionsHome/questionTypes/questionTypeEditor";

    public function libraryAction(){
        $view=new ViewModel();
        $view->setTemplate("questions/edit/question_type/library");
        $view->setTerminal(true);
        $this->getResponse()->getHeaders()->addHeaderLine("Cache-Control", 'max-age=2592000');
        $this->getResponse()->getHeaders()->addHeaderLine('Content-Type', 'text/javascript');
        return $view;
    }
    /**
     * @param QuestionTypeManager $question
     */
    public function ReRouteToQuestionEditor($question)
    {
        header("Location: /questions/question-types/{$question->getQuestionType()->getQuestionTypeID()}");
        exit();
    }
    public function getQuestionType(){

        /*******************************************************************/
        /* Safety Check                                                    */
        /*******************************************************************/
        $questionID=$this->params()->fromRoute("questionTypeId");
        if(!isset($questionID)){
            QuestionTypeManager::ExitWithError("Question ID was not found in the Route");
            return null;
        }

        /*******************************************************************/
        /* Verify question type id                                         */
        /*******************************************************************/
        $returnedQuestion=new QuestionTypeManager($questionID);
        if($questionID!=$returnedQuestion->getQuestionType()->getQuestionTypeID()){
            $this->ReRouteToQuestionEditor($returnedQuestion);
        }

        /*******************************************************************/
        return $returnedQuestion;
    }


    /***********************************************************************/
    /* Public Access                                                       */
    /***********************************************************************/
    public function indexAction(){
        $view =new ViewModel();
        $view->setTemplate("/questions/edit/question_type/index");
        $view->setVariable("types",Info::QuestionTypesTable()->fetch());

        return $view;
    }
    /***********************************************************************/
    public function JsonView($object)
    {
        $view =new ViewModel();
        $view->setTemplate("application/tools/json");

        Info::getEvent()->getViewModel()->setTemplate("layout/empty");

        $view->setVariable("object",$object);
        return $view;
    }

    /***********************************************************************/
    /* Editor                                                              */
    /***********************************************************************/
    public function editorAction(){
        $view =new ViewModel();
        $view->setTemplate("questions/edit/question_type/editor");
        $this->getQuestionType();

        return $view;
    }

    /***********************************************************************/
    public function loadAction(){

        $questionType=$this->getQuestionType();
        $returnData=array(
            "creator"=>$questionType->getDevelopmentCode(),
            "display"=>$questionType->getDeploymentCode()
        );

        return $this->JsonView($returnData);
    }

    /***********************************************************************/
    public function saveAction(){

        $questionType=$this->getQuestionType();
        $content=Info::getBodyJSON();

        if(isset($content["display"]) && isset($content["creator"])){
            $questionType->setDeploymentCode($content["display"]);
            $questionType->setDevelopmentCode($content["creator"]);

            return $this->JsonView(array("success"=>true));
        }
        return $this->JsonView(array("success"=>false,"error"=>"Not all the perameters were there"));
    }

    /***********************************************************************/
    public function createAction()
    {
        if($this->getRequest()->isPost()){
            $name=$this->params()->fromPost("name");
            /*******************************************************************/
            if(!isset($name)){
                return $this->JsonView(array("success"=>false,"error"=>"Missing Name..."));
            }

            /*******************************************************************/
            $questionType=QuestionTypeManager::Create($name);

            /*******************************************************************/
            $this->ReRouteToQuestionEditor($questionType);
            return null;
        }

        $view=new ViewModel();
        $view->setTemplate("questions/edit/question-type/create");

        return $view;


    }
}