<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Instructor\Controller\Index' => 'Instructor\Controller\IndexController',
            'Instructor\Controller\User' => 'Instructor\Controller\UserController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'instructor' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/instructor',
                    'defaults' => array(
                        'controller' => 'Instructor\Controller\User',
                        'action'     => 'index',
                        'roles' => array(
                            Roles::$INSTRUCTOR
                        ),
                        'title'=>"Home"
                    ),

                ),
                'may_terminate' => true,
                'child_routes' => array(
                    // Segment route for viewing one blog post
                    'section' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/section/[:sectionID]',
                            'constraints'=>array(
                                "sectionID"=>'[a-zA-Z0-9_-]+',
                            ),
                            'defaults' => array(
                                'controller' => 'Instructor\Controller\User',
                                'action'     => 'sectionHome',

                                'roles' => array(
                                    Roles::$INSTRUCTOR
                                ),
                                'title'=>"Section Home"
                            ),
                        ),
                    ),
                    'login' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/login',
                            'defaults' => array(
                                'controller' => 'Instructor\Controller\Index',
                                'action'     => 'login',
                                'roles' => array(
                                    Roles::$GUEST
                                ),
                                'title'=>"Login"
                            ),
                        ),
                    ),
                    'logout' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/logout',
                            'defaults' => array(
                                'controller' => 'Instructor\Controller\User',
                                'action'     => 'logout',
                                'roles' => array(
                                    Roles::$INSTRUCTOR
                                ),
                                'title'=>"Logout"
                            ),
                        ),
                    ),
                    'invitation' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/invitation/[:invitationID]',
                            'constraints' => array(
                                'invitationID' => '[a-zA-Z0-9_-]+',
                            ),
                            'defaults' => array(
                                'controller' => 'Instructor\Controller\Index',
                                'action'     => 'invitation',
                                'roles' => array(
                                    Roles::$INSTRUCTOR
                                ),
                                'title'=>"Invitation"
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'register'=>array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/register',
                                    'defaults' => array(
                                        'controller' => 'Instructor\Controller\Index',
                                        'action'     => 'register',
                                        'roles' => array(
                                            Roles::$GUEST
                                        ),
                                        'title'=>"Register"
                                    ),
                                )
                            )
                        )
                    ),


                ),
            ),

        ),
    ),
);