<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Administrator\Controller\Index' => 'Administrator\Controller\IndexController',
            'Administrator\Controller\User' => 'Administrator\Controller\UserController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'administrator' => array(
                'type' => 'segment',
                'options' => array(
                    'route'    => '/admin[istrator]',
                    'defaults' => array(
                        'controller' => 'Administrator\Controller\User',
                        'action'     => 'index',
                        'roles' => array(
                            Roles::$ADMIN
                        ),
                        'title'=>"Home"
                    ),

                ),
                'may_terminate' => true,
                'child_routes' => array(
                    // Segment route for viewing one blog post
                    'login' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/login',
                            'defaults' => array(
                                'controller' => 'Administrator\Controller\Index',
                                'action'     => 'login',
                                'roles' => array(
                                    Roles::$GUEST
                                ),
                                'title'=>"Login"
                            ),
                        ),
                    ),
                    'logout' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/logout',
                            'defaults' => array(
                                'controller' => 'Administrator\Controller\User',
                                'action'     => 'logout',
                                'roles' => array(
                                    Roles::$ADMIN
                                ),
                                'title'=>"Logout"
                            ),
                        ),
                    ),
                    'invitations' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/invitations',
                            'defaults' => array(
                                'controller' => 'Administrator\Controller\User',
                                'action'     => 'invitations',
                                'roles' => array(
                                    Roles::$ADMIN
                                ),
                                'title'=>"Invitations"
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            // Segment route for viewing one blog post
                            'create' => array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/create',
                                    'defaults' => array(
                                        'controller' => 'Administrator\Controller\User',
                                        'action'     => 'createInvitation',
                                        'roles' => array(
                                            Roles::$ADMIN
                                        ),
                                        'title'=>"Create Invitation"
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'courses' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/courses',
                            'defaults' => array(
                                'controller' => 'Administrator\Controller\User',
                                'action'     => 'courses',
                                'roles' => array(
                                    Roles::$ADMIN
                                ),
                                'title'=>"Courses"
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            // Segment route for viewing one blog post
                            'course' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/[:CourseCategory]_[:courseID]',
                                    'constraints' => array(
                                        'CourseCategory' => '[A-Z]+',
                                        'courseID' => '[0-9]+',
                                    ),
                                    'defaults' => array(
                                        'controller' => 'Administrator\Controller\User',
                                        'action'     => 'courseDetails',
                                        'roles' => array(
                                            Roles::$ADMIN
                                        ),
                                        'title'=>"Course Details"
                                    ),

                                ),
                                'may_terminate' => true,
                                'child_routes' => array(
                                    // Segment route for viewing one blog post
                                    'sections' => array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/sections',
                                            'defaults' => array(
                                                'controller' => 'Administrator\Controller\User',
                                                'action'     => 'sections',
                                                'roles' => array(
                                                    Roles::$ADMIN
                                                ),
                                                'title'=>"Course Subjects"
                                            ),

                                        ),
                                        'may_terminate' => true,
                                        'child_routes' => array(
                                            'section' => array(
                                                'type' => 'segment',
                                                'options' => array(
                                                    'route' => '/[:sectionID]',
                                                    'constraints' => array(
                                                        'sectionID' => '[0-9]+'
                                                    ),
                                                    'defaults' => array(
                                                        'controller' => 'Administrator\Controller\User',
                                                        'action'     => 'sectionDetails',
                                                        'roles' => array(
                                                            Roles::$ADMIN
                                                        ),
                                                        'title'=>"Subject Details"
                                                    ),

                                                ),
                                            ),
                                            'add-section'=>array(
                                                'type' => 'literal',
                                                'options' => array(
                                                    'route' => '/add',
                                                    'defaults' => array(
                                                        'controller' => 'Administrator\Controller\User',
                                                        'action'     => 'addSection',
                                                        'roles' => array(
                                                            Roles::$ADMIN
                                                        ),
                                                        'title'=>"Create Subject"
                                                    ),
                                                ),
                                            )
                                        )
                                    ),

                                )
                            ),
                            'login' => array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/add-course',
                                    'defaults' => array(
                                        'controller' => 'Administrator\Controller\User',
                                        'action'     => 'addCourses',
                                        'roles' => array(
                                            Roles::$ADMIN
                                        ),
                                        'title'=>"Create Course"
                                    ),
                                ),
                            ),
                        ),
                    ),

                ),
            ),

        ),
    ),
);