<?php
namespace Files\Controller;

use Application\Info;
use Application\Model\CourseContent;
use Application\Roles;
use Files\Service\CourseContentItemManager;
use Slim\View;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/2/2017
 * Time: 3:12 AM
 */
class IndexController extends AbstractActionController
{
    protected $SetupActions=array();

    /**
     * @param MvcEvent $e
     * @return mixed
     */
    public function onDispatch(MvcEvent $e)
    {
        $navigation=new ViewModel();
        $navigation->setTemplate("layout/navigation");

        $banner=new ViewModel();
        $banner->setTemplate("layout/banner");

        $e->getViewModel()->addChild($navigation,"navigation");
        $e->getViewModel()->addChild($banner,"banner");
        //e->getViewModel()->setTemplate("visitors/layout");



        /**
         * @param IndexController $controller
         * @param CourseContent $courseContent
         * @return ViewModel
         */
        $this->SetupActions["assessment"]=function($controller,$courseContent){
            $controller->redirect()->toUrl("/assessments/create?CourseContentID={$courseContent->getContentID()}");
            return new ViewModel();
        };

        /**
         * @param IndexController $controller
         * @param CourseContent $courseContent
         * @return ViewModel
         */

        $this->SetupActions["magic-points"]=function($controller,$courseContent){

            $properties=$courseContent->getProperties();
            $rows=intval($properties["GridSize"]["Rows"]);
            $columns=intval($properties["GridSize"]["Columns"]);

            for($row=0;$row<$rows;$row++){
                for($column=0;$column<$columns;$column++)
                {
                    $cell=$properties["Grid"][$row][$column];
                    if(isset($cell["QuestionID"])){
                        $questionID=Info::ActiveQuestionsTable()->AddQuestion(
                            $cell["QuestionID"],
                            $properties["SessionID"],
                            "[$row,$column]",
                            "MagicPoints",
                            array(
                                "PointsWorth"=>$cell["Weight"],
                                "Attempts"=>0,
                                "AllowedAttempts"=>1));

                        $properties["Grid"][$row][$column]["ActiveQuestionID"]=$questionID->getAnsweredID();

                    }
                }
            }
            $properties=json_encode($properties);

            Info::CourseContentTable()->Update($courseContent->getContentID(),array("Properties"=>$properties));

            $controller->redirect()->toRoute("course-content",array_merge($controller->params()->fromRoute(),array("contentID"=>$courseContent->getContentID())));
            return new ViewModel();
        };

        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub

        return $parent;//parent::onDispatch($e); // TODO: Change the autogenerated stub


    }

    /***********************************************************************/
    public function indexAction()
    {
        $this->redirect()->toRoute("course-content/view",array("contentID"=>$this->params()->fromRoute('contentID')));
        return;
    }

    /***********************************************************************/
    public function viewAction()
    {
        $contentID=$this->params()->fromRoute("contentID");

        $courseContentManager=new CourseContent();
        $courseContentManager->exchangeArray(array("ContentID"=>$contentID));
        $view=new ViewModel();
        $view->setVariable("contentItem",$courseContentManager);
        $view->setTemplate("files/display");
        return $view;
    }

    /***********************************************************************/
    public function runAction()
    {
        $contentID=$this->params()->fromRoute("contentID");

        $courseContentManager=Info::CourseContentTable()->getByID($contentID);
        $view=new ViewModel();
        $view->setVariable("contentItem",$courseContentManager);
        $view->setTemplate("files/run");
        $view->setTerminal(true);
        return $view;
    }
    public function FindAvailableFileName($extension){
        $folder="data/Files";
        $files = glob($folder . "*.$extension");
        $index=count($files);
        while(file_exists("$folder/File$index.$extension")){
            $index++;
        }
        return "$folder/File$index.$extension";
    }
    public function FindFiles_Copy_Update($data){

        if(isset($data["name"]) &&
            isset($data["type"]) &&
            isset($data["tmp_name"]) &&
            isset($data["error"]) &&
            isset($data["size"]))
        {
            $fileInfo=pathinfo($data["name"]);
            $fileCopingTo=$this->FindAvailableFileName($fileInfo["extension"]);
            copy($data["tmp_name"],$fileCopingTo);
            return array("Path"=>$fileCopingTo,"Type"=>$data["type"]);

        }

        $newData=array();
        foreach($data as $key => $value){
            if(!is_array($value)){
                $newData[$key]=$value;
                continue;
            }
            $newData[$key]=$this->FindFiles_Copy_Update($value);
        }
        return $newData;
    }
    public function ConvertJsonToStringJsonFirstPass($data){

        $newData=array();
        foreach($data as $key => $value){

            /***************************************************************/
            if(!is_array($value)){
                $newData[$key]=$value;
                continue;
            }
            /***************************************************************/
            if($key==='UUID'){

                foreach($data["UUID"] as $key2 => $value2){
                    $newData[$key2]=uniqid();
                }
                continue;
            }
            $newData[$key]=$this->ConvertJsonToStringJsonFirstPass($value);
        }
        return $newData;
    }
    public function ConvertJsonToStringJsonSecondPass($data){

        $newData=array();
        foreach($data as $key => $value){

            /***************************************************************/
            if(!is_array($value)){
                $newData[$key]=$value;
                continue;
            }

            /***************************************************************/
            if($key=='Json'){
                foreach($data["Json"] as $key2 => $value2){
                    $newData[$key2]=json_encode($value2);
                }
                continue;
            }
            $newData[$key]=$this->ConvertJsonToStringJsonSecondPass($value);
        }
        return $newData;
    }

    public function BasicTextReplacing($data, $search, $replace, &$bool){

        $newData=array();
        foreach($data as $key => $value){

            /***************************************************************/
            if(!is_array($value)){
                $newData[$key]=$value;
                $replaced=preg_replace($search,$replace,$newData[$key]);
                if($replaced!=$newData[$key]){
                    $bool=true;
                }
                $newData[$key]=$replaced;
                continue;
            }


            $newData[$key]=$this->BasicTextReplacing($value,$search,$replace,$bool);
        }
        return $newData;
    }
    /***********************************************************************/
    public function createAction()
    {
        if($this->getRequest()->isPost())
        {
            /***************************************************************/
            /* Merge All File and Post Content                             */
            /***************************************************************/
            $data=$_POST;

            $files=$this->getRequest()->getFiles()->toArray();
            $data=array_replace_recursive($data,$files);

            /***************************************************************/
            /* Change Data Insert Into The Database                        */
            /***************************************************************/
            $data=$this->FindFiles_Copy_Update($data);
            $data=$this->ConvertJsonToStringJsonFirstPass($data);
            $data=$this->ConvertJsonToStringJsonSecondPass($data);

            /***************************************************************/
            /* Insert Into Database                                        */
            /***************************************************************/
            $id=Info::CourseContentTable()->Insert($data["Content"]);

            /***************************************************************/
            /* If some Attributes Depended on the ID of the item, then fix */
            /* and Update                                                  */
            /***************************************************************/
            $didSomethingChange=false;
            $data=$this->BasicTextReplacing($data, '/__ID__/',"".$id,$didSomethingChange);
            if($didSomethingChange){
                Info::CourseContentTable()->Update($id,$data["Content"]);
            }


            /***************************************************************/
            /* Needed Setups                                               */
            /***************************************************************/
            if(isset($this->SetupActions[$data["Content"]["Type"]])){
                return $this->SetupActions[$data["Content"]["Type"]]($this,Info::CourseContentTable()->getByID($id));
            }

            /***************************************************************/
            /* Redirect                                                    */
            /***************************************************************/
            $redirect=$data["Redirect"];
            header("Location: {$redirect}");
            exit();

        }
        $this->redirect()->toUrl(Roles::GetRoleUrl("")); // TODO Change to course home or something



    }
    public function setupAction()
    {
        $contentID=$this->params()->fromRoute("contentID");

        $courseContentManager=Info::CourseContentTable()->getByID($contentID);

        if($courseContentManager->isSetup()){
            $this->redirect()->toRoute("course-content",$this->params()->fromRoute());
            return new ViewModel();
        }



        $this->redirect()->toRoute("course-content",$this->params()->fromRoute());
    }



}