<?php
use Application\Info;
use Application\Model\Assessment;
use Application\Model\RunningAssessment;
use Application\Roles;

/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/9/2017
 * Time: 6:18 AM
 */

/** @var Assessment $Assessment */
if(isset($this->Assessment)){
    $Assessment=$this->Assessment;
}
/** @var RunningAssessment $RunningAssessment */
$RunningAssessment=Info::AssessmentTable()->getRunningInstance($Assessment,Info::getCurrentUser()); ////TODO NEEDS ATENTION


if(Info::LoginService()->IsAuthorized(array(Roles::$INSTRUCTOR,Roles::$ADMIN,Roles::$TA))){
    echo $this->partial("assessments/edit.phtml",array("Assessment"=>$Assessment));
}
else if(Info::LoginService()->IsAuthorized(Roles::$STUDENT))
{
     ?>

    <?php

    if($RunningAssessment!=null)
    {
        ?>
        <div api-component="RunningAssessments" api-fetcher="get" api-parameter-id="<?php echo $RunningAssessment->getAnsweredID()  ?>">
            <div api-attribute="Assessment->Name"></div>
            <div api-attribute-link="urls->view" api-link-new-window class="btn btn-default">Resume Assessment</div>
            <div api-attribute="Questions">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Question ID</th>
                            <th>Question</th>
                            <th>Type</th>
                            <th>Weight</th>
                        </tr>
                    </thead>
                    <tbody api-drop-here="Questions">
                        <tr api-array-template api-attribute-save="Questions->Attempts" api-attribute-saveas="attempts">
                            <td api-attribute="Questions->QuestionID"></td>
                            <td api-attribute="Questions->Question->Question"></td>
                            <td api-attribute="Questions->Question->QuestionType"></td>
                            <td api-attribute="Questions->Question->Weight"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <?php
    }
    else
    {

        ?>
        <div api-component="Assessments" api-fetcher="get" api-parameter-id="<?php echo $Assessment->getAssessmentID()  ?>">
            <div api-attribute="Name"></div>
            <div api-action="start-assessment" class="btn btn-default">Start Assessment</div>
            <div api-render='questions'></div>
        </div>
        <?php
    }
}
else{
    echo "<h1 class='text-danger'>Unexpected Error Has Occored. Please login back it</h1>";
}