<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/9/2017
 * Time: 8:23 AM
 */


/** @var String $Type */
/** @var \Application\Model\Question $Question */
/** @var String $this->QuestionSessionID */
/** @var String $this->SessionID */
/** @var \Application\Model\AssessmentQuestion $AssessmentQuestion */




echo $this->partial("/questions/edit/question/view.phtml",
    array("question"=>$this->Question,
          "answerURL"=>"/questions/answer/{$this->SessionID}/{$this->QuestionSessionID}/{$this->Question->getQuestionID()}/{$this->Type}?PointsWorth={$this->AssessmentQuestion->getWeight()}"));