<?php

namespace Questions\Controller;
use Application\Info;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 5:39 AM
 */
class IndexController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {
        /*******************************************************************/
        /* User Check                                                      */
        /*******************************************************************/
        $this->getEventManager()->trigger( "authenticating",$this,array( "roles"=> array(__NAMESPACE__)));


        $navigation=new ViewModel();
        $navigation->setTemplate("layout/staff/navigation");



        $e->getViewModel()->addChild($navigation,"navigation");;
        //e->getViewModel()->setTemplate("visitors/layout");
        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub


        /*******************************************************************/




        /*******************************************************************/
        return $parent;
    }
    public function indexAction(){
        $view=new ViewModel();
        $view->setTemplate('questions/index');
        return $view;
    }
}