<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/21/2017
 * Time: 9:47 AM
 */
?>
<h1>Welcome to Admins Home</h1>

<div class="col-lg-3">
    <a href="admin/courses"  class="btn btn-block btn-primary">Courses</a>
    <a href="admin/invitations" class=" btn btn-block btn-primary">Invitations</a>
    <a href="/questions" class=" btn btn-block btn-primary">Questions</a>
</div>
<div id='main' class="col-lg-5">

</div>
<div id='sub-main' class="col-lg-4">

</div>