<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/23/2017
 * Time: 10:17 AM
 */
?>
<div class="col-lg-4">
<?php
if(isset($error)){
    ?>
    <form action="/admin/login" method="post">
        <div class="form-group row has-danger">
            <label for="userName" class="col-2 col-from-label">User Name:</label>
            <div class="col-10">
                <input name='userName' id="userName" class="form-control form-control-danger" type="text" placeholder="User Name...">
            </div>
        </div>
        <div class="form-group row has-danger">
            <label for="password" class="col-2 col-from-label">Password</label>
            <div class="col-10">
                <input name='password' id="password" class="form-control form-control-danger" type="password" placeholder="Password...">

            </div>
        </div>
        <span class="text-danger"><?php echo $error; ?></span>
        <input class="btn btn-default form-control" type="submit" value="Login"/>


    </form>
<?php
}
else {


    ?>

    <form action="/admin/login" method="post">
        <div class="form-group row">
            <label for="userName" class="col-2 col-from-label">User Name:</label>
            <div class="col-10">
                <input name='userName' id="userName" class="form-control" type="text" placeholder="User Name...">
            </div>
        </div>
        <div class="form-group row">
            <label for="password" class="col-2 col-from-label">Password</label>
            <div class="col-10">
                <input name='password' id="password" class="form-control" type="password" placeholder="Password...">
            </div>
        </div>
        <input class="btn btn-default form-control" type="submit" value="Login"/>
    </form>
    <?php
}
?>
</div>
