<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/23/2017
 * Time: 6:55 PM
 */

?>
<form action="<?php echo \Application\Info::Url() ?>" method="post">

    <div class="form-group row">
        <label for="sectionNumber" class="col-2 col-from-label">sectionNumber</label>
        <div class="col-10">
            <input name='SectionNumber' id="sectionNumber" class="form-control" type="text" placeholder="Section Number...">
        </div>
    </div>

    <input class="btn btn-default form-control" type="submit" value="Login"/>
</form>
