<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/23/2017
 * Time: 6:22 PM
 */

use Application\Model\Section;

/** @var \Application\Model\Course $course */

?>

<div class="modal fade" id="exampleModalLong2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="ajax-load modal-body" load="<?php echo \Application\Info::Url()."/add" ?>">

            </div>
            <!-- <div class="modal-footer"> -->
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            <!-- </div> -->
        </div>
    </div>
</div>

<p>
    <a  data-toggle="modal" data-target="#exampleModalLong2" class="btn btn-primary">Add Section</a>
</p>
<div class="list-group">
<?php
/** @var Section $section */
foreach($sections as $section) {
    echo "<a class='list-group-item' href='{$this->url('administrator/courses/course/sections/section',array_merge($parameters,array("sectionID"=>$section->getSectionNumber())))}'>{$section->getSectionNumber()}</a>";
}
?>
</div>
