<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Student\Controller;

use Application\Info;
use Application\Roles;
use Zend\Mvc\Application;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Zend\Mvc\MvcEvent;
use Zend\View\View;

class IndexController extends AbstractActionController
{


    public function onDispatch(MvcEvent $e)
    {
        /*******************************************************************/
        $navigation=new ViewModel();
        $navigation->setTemplate("layout/staff/navigation");

        /*******************************************************************/
        $e->getViewModel()->addChild($navigation,"navigation");
        //e->getViewModel()->setTemplate("visitors/layout");
        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub


        /*******************************************************************/
        return $parent;
    }


    public function loginAction()
    {
        if(Info::LoginService()->IsAlreadySignedIn(Roles::$STUDENT)){
            $this->redirect()->toRoute("student");
            return new ViewModel();
        }

        /*******************************************************************/
        if (!$this->getRequest()->isPost())
        {
            $view=new ViewModel();
            $view->setVariable("url","student/login");
            $view->setTemplate("user/login");
            return $view;
        }

        /*******************************************************************/
        $UserName=$this->params()->fromPost("userName");
        $Password=$this->params()->fromPost("password");

        if(($userSession=Info::LoginService()->SignIn($UserName,$Password,"Student"))!=null){
            $this->redirect()->toRoute("student");
            return;
        }

        $view=new ViewModel();
        $view->setVariable("error","Username and Password was not found");
        $view->setVariable("url","student/login");
        $view->setTemplate("user/login");
        return $view;


    }


}
