<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'display_not_found_reason' => true,
        'display_exceptions'       => true,
        'doctype'                  => 'HTML5',
        'not_found_template'       => 'error/404',
        'exception_template'       => 'error/index',
        'template_map' => array(
            //'layout/layout'           => __DIR__ . '/../view/layout/layout.phtml',
        ),
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Questions\Controller\Index' => 'Questions\Controller\IndexController',
            'Questions\Controller\Questions' => 'Questions\Controller\QuestionsController',
            'Questions\Controller\QuestionTypes' => 'Questions\Controller\QuestionTypeController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'questions' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/questions',
                    'defaults' => array(
                        'controller' => 'Questions\Controller\Index',
                        'action'     => 'index',
                        'roles' => array(
                            Roles::$INSTRUCTOR,
                            Roles::$ADMIN,
                            Roles::$TA,
                        ),
                        'title'=>"Home"
                    ),

                ),
                'may_terminate' => true,
                'child_routes' => array(
                    // Segment route for viewing one blog post
                    'upload' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/upload',
                            'defaults' => array(
                                'controller' => 'Questions\Controller\Questions',
                                'action'     => 'upload',
                                'roles' => array(
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN,
                                    Roles::$TA,
                                ),
                                'title'=>"Types"
                            ),
                        ),
                    ),
                    'library' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/library',
                            'defaults' => array(
                                'controller' => 'Questions\Controller\QuestionTypes',
                                'action'     => 'library',
                                'roles' => array(
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN,
                                    Roles::$STUDENT,
                                    Roles::$TA,
                                ),
                                'title'=>"Types"
                            ),
                        ),
                    ),
                    'questions-answer' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/answer/[:AnswerID]',
                            'constraints' => array(
                                'AnswerID' => '[a-zA-Z0-9-_]+'
                            ),
                            'defaults' => array(
                                'controller' => 'Questions\Controller\Questions',
                                'action'     => 'answer',
                                'roles' => array(
                                    Roles::$STUDENT
                                ),
                                'title'=>"Types"
                            ),
                        ),
                    ),
                    'questionTypes' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/question-types',
                            'defaults' => array(
                                'controller' => 'Questions\Controller\QuestionTypes',
                                'action'     => 'index',
                                'roles' => array(
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN,
                                    Roles::$TA,
                                ),
                                'title'=>"Types"
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'questionType_create' => array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/create',
                                    'defaults' => array(
                                        'controller' => 'Questions\Controller\QuestionTypes',
                                        'action'     => 'create',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN,
                                            Roles::$TA,
                                        ),
                                        'title'=>"Create Type"
                                    ),
                                ),
                            ),
                            'questionType_editor' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/[:questionTypeId]',
                                    'constraints' => array(
                                        'questionTypeId' => '[0-9]+',
                                    ),
                                    'defaults' => array(
                                        'controller' => 'Questions\Controller\QuestionTypes',
                                        'action'     => 'editor',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN,
                                            Roles::$TA,
                                        ),
                                        'title'=>"Editor Type"
                                    ),
                                ),
                                'may_terminate' => true,
                                'child_routes' => array(
                                    'questionType_save' => array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/save',
                                            'defaults' => array(
                                                'controller' => 'Questions\Controller\QuestionTypes',
                                                'action'     => 'save',
                                                'roles' => array(
                                                    Roles::$INSTRUCTOR,
                                                    Roles::$ADMIN,
                                                    Roles::$TA,
                                                ),
                                                'title'=>"Save Type"
                                            ),
                                        ),
                                    ),
                                    'questionType_load' => array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/load',
                                            'defaults' => array(
                                                'controller' => 'Questions\Controller\QuestionTypes',
                                                'action'     => 'load',
                                                'roles' => array(
                                                    Roles::$INSTRUCTOR,
                                                    Roles::$ADMIN,
                                                    Roles::$TA,
                                                    Roles::$STUDENT
                                                ),
                                                'title'=>"Load Type"
                                            ),
                                        ),
                                    )
                                )
                            )
                        )
                    ),
                    'questionsInd' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/questions',
                            'defaults' => array(
                                'controller' => 'Questions\Controller\Questions',
                                'action'     => 'index',
                                'roles' => array(
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN,
                                    Roles::$TA,
                                ),
                                'title'=>"Collection"
                            ),
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            'questionsInd_create' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/create',
                                    'defaults' => array(
                                        'controller' => 'Questions\Controller\Questions',
                                        'action'     => 'create',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN,
                                            Roles::$TA,
                                        ),
                                        'title'=>"Create Question"
                                    ),
                                ),
                            ),
                            'questionsInd_creator' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/create/[:questionTypeId]',
                                    'constraints' => array(
                                        'questionTypeId' => '[0-9]+',
                                    ),
                                    'defaults' => array(
                                        'controller' => 'Questions\Controller\Questions',
                                        'action'     => 'create',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN,
                                            Roles::$TA,
                                        ),
                                        'title'=>"Create Question"
                                    ),
                                ),
                            ),
                            'questionsInd_Use' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/[:questionId]',
                                    'constraints' => array(
                                        'questionId' => '[0-9]+',
                                    ),
                                    'defaults' => array(
                                        'controller' => 'Questions\Controller\Questions',
                                        'action'     => 'details',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN,
                                            Roles::$TA,
                                            Roles::$STUDENT
                                        ),
                                        'title'=>"View"
                                    ),
                                ),
                                'may_terminate' => true,
                                'child_routes' => array(
                                    'uestionsInd_runable' => array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/run',
                                            'defaults' => array(
                                                'controller' => 'Questions\Controller\Questions',
                                                'action'     => 'run',
                                                'roles' => array(
                                                    Roles::$INSTRUCTOR,
                                                    Roles::$ADMIN,
                                                    Roles::$TA,
                                                    Roles::$STUDENT
                                                ),
                                                'title'=>"Run"
                                            ),
                                        ),
                                        'may_terminate' => true,
                                        'child_routes' => array(
                                            'uestionsInd_test' => array(
                                                'type' => 'literal',
                                                'options' => array(
                                                    'route' => '/test',
                                                    'defaults' => array(
                                                        'controller' => 'Questions\Controller\Questions',
                                                        'action'     => 'test',
                                                        'roles' => array(
                                                            Roles::$INSTRUCTOR,
                                                            Roles::$ADMIN,
                                                            Roles::$TA,
                                                            Roles::$STUDENT
                                                        ),
                                                        'title'=>"Test"
                                                    ),
                                                ),
                                            ),
                                            'questionsRun_load' => array(
                                                'type' => 'literal',
                                                'options' => array(
                                                    'route' => '/load',
                                                    'defaults' => array(
                                                        'controller' => 'Questions\Controller\Questions',
                                                        'action'     => 'loadView',
                                                        'roles' => array(
                                                            Roles::$INSTRUCTOR,
                                                            Roles::$ADMIN,
                                                            Roles::$TA,
                                                            Roles::$STUDENT
                                                        ),
                                                        'title'=>"Load"
                                                    ),
                                                ),
                                            )
                                        )
                                    ),
                                    'questionsInd_editor' => array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/editor',
                                            'defaults' => array(
                                                'controller' => 'Questions\Controller\Questions',
                                                'action'     => 'editor',
                                                'roles' => array(
                                                    Roles::$INSTRUCTOR,
                                                    Roles::$ADMIN,
                                                    Roles::$TA
                                                ),
                                                'title'=>"Editor"
                                            ),
                                        ),
                                        'may_terminate' => true,
                                        'child_routes' => array(
                                            'questionsInd_save' => array(
                                                'type' => 'literal',
                                                'options' => array(
                                                    'route' => '/save',
                                                    'defaults' => array(
                                                        'controller' => 'Questions\Controller\Questions',
                                                        'action'     => 'save',
                                                        'roles' => array(
                                                            Roles::$INSTRUCTOR,
                                                            Roles::$ADMIN,
                                                            Roles::$TA
                                                        ),
                                                        'title'=>"Save"
                                                    ),
                                                ),
                                            ),
                                            'questionsInd_load' => array(
                                                'type' => 'literal',
                                                'options' => array(
                                                    'route' => '/load',
                                                    'defaults' => array(
                                                        'controller' => 'Questions\Controller\Questions',
                                                        'action'     => 'load',
                                                        'roles' => array(
                                                            Roles::$INSTRUCTOR,
                                                            Roles::$ADMIN,
                                                            Roles::$TA,
                                                            Roles::$STUDENT
                                                        ),
                                                        'title'=>"Load"
                                                    ),
                                                ),
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),
                )
            )
        )
// Uncomment below to add routes
//        'routes' => array(
//            'questions' => array(
//                'type' => 'Literal',
//                'options' => array(
//                    'route' => '/questions',
//                    'defaults' => array(
//                        '__NAMESPACE__' => 'Questions\Controller',
//                        'controller' => 'Questions',
//                        'action' => 'index',
//                    )
//                )
//            )
//        ),
//        'may_terminate' => true,
//        'child_routes' => array(
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            )
//        )
    )
);