<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Administrator\Controller;

use Application\Info;
use Application\Roles;
use Zend\Mvc\Application;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Zend\Mvc\MvcEvent;
use Zend\View\View;

class IndexController extends AbstractActionController
{

    /***********************************************************************/
    public function onDispatch(MvcEvent $e)
    {


        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub

        $navigation=new ViewModel();
        $navigation->setTemplate("layout/staff/navigation");

        $e->getViewModel()->addChild($navigation,"navigation");


        /*******************************************************************/
        return $parent;
    }

    /***********************************************************************/
    public function loginAction()
    {

        if(Info::LoginService()->IsAlreadySignedIn(Roles::$ADMIN)){
            $this->redirect()->toRoute("administrator");
            return new ViewModel();
        }


        /*******************************************************************/
        /* Login Page                                                      */
        /*******************************************************************/
        if (!$this->getRequest()->isPost())
        {
            $view=new ViewModel();
            $view->setVariable("url","/administrator/login");
            $view->setTemplate("user/login");
            return $view;
        }

        /*******************************************************************/
        $view=new ViewModel();
        $view->setTemplate("user/login");
        $view->setVariable("error","Username and Password was not found");
        $view->setVariable("url","/administrator/login");

        /*******************************************************************/
        $UserName=$this->params()->fromPost("userName");
        $Password=$this->params()->fromPost("password");

        if((Info::LoginService()->SignIn($UserName,$Password,"Administrator"))!=null){
            $this->redirect()->toRoute("administrator");
        }



        return $view;



    }



}
