<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 2/27/2017
 * Time: 6:21 AM
 */
use Application\Info;


?>
<h1>Where all your questions can be answered... <img height="50px" src="http://4.bp.blogspot.com/-_F3Cza63WK4/U52CxFX8d-I/AAAAAAAAJY4/0vyNz8InZko/s1600/smiley-laughing-out-loud.png"></h1>
<div class="question-and-types-container">
    <div class="col-lg-8 questions-container">
        <div api-component="Questions" api-fetcher="get">
            <div class="tool-bar-for-questions">

            </div>
            <table class="table questions-table">
                <thead>
                <tr>
                    <th></th>
                    <th>Question ID</th>
                    <th>Question</th>
                </tr>
                </thead>
                <tbody api-drop-here>
                <tr api-array-template api-data-export>
                    <td ><span api-attribute-link="Edit"  api-link-new-window>Open</span></td>
                    <td api-attribute="QuestionID"></td>
                    <td api-attribute="Question"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-lg-4 question-type-container">
        <div api-component="QuestionTypes" api-fetcher="get">
            <div  api-array-template api-attribute-save="QuestionTypeID" api-attribute-saveas="api-data-questiontypeid">
                <div api-attribute="Name"></div>
                <div class="contactInfo">
                    <div api-attribute="CreatedByUser->FirstName"></div>
                    <div api-attribute="CreatedByUser->LastName"></div>
                    <div api-attribute="CreatedByUser->Email"></div>
                    <div api-attribute="CreatedByUser->PhoneNumber"></div>
                </div>
                <div class="options">
                    <div api-attribute-link="Edit" api-link-new-window class="make-a-question-btn"></div>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
$(document).ready(function(){
    $("[api-component='Questions']").on("click","tr[api-data-expectedanswer]",function(){
        var questionTypes=$("[api-component='QuestionTypes']");
        questionTypes.find("[is-selected]").removeAttr("is-selected");
        questionTypes.find("[api-data-questiontypeid='"+$(this).attr("api-data-questiontypeid")+"']").attr("is-selected",true);
        $(".question-and-types-container").attr("is-selected",true);
    });

});
</script>
<!--<a href="--><?php //echo Info::Url() ?><!--/question-types" class="btn btn-primary">Question Types</a>-->
<!--<a href="--><?php //echo Info::Url() ?><!--/questions" class="btn btn-primary">Questions</a>-->
