<?php

namespace React\Controller;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 4/5/2017
 * Time: 8:04 PM
 */
class IndexController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {
        /*******************************************************************/
        $parent=parent::onDispatch($e); // TODO: Change the autogenerated stub


        /*******************************************************************/
        return $parent;
    }
    public function indexAction(){

        $view=new ViewModel();
        $view->setTemplate('react/index');
        return $view;
    }
}