<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'TA\Controller\Index' => 'TA\Controller\IndexController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'ta' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/ta',
                    'defaults' => array(
                        'controller' => 'TA\Controller\Index',
                        'action'     => 'index',
                        'roles' => array(
                            Roles::$TA
                        ),
                        'title'=>"Home"
                    ),

                ),
                'may_terminate' => true,
                'child_routes' => array(
                    // Segment route for viewing one blog post
                    'login' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/login',
                            'defaults' => array(
                                'controller' => 'TA\Controller\Index',
                                'action'     => 'login',
                                'roles' => array(
                                    Roles::$GUEST
                                ),
                                'title'=>"Login"
                            ),
                        ),
                    ),
                    'logout' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/logout',
                            'defaults' => array(
                                'controller' => 'TA\Controller\Index',
                                'action'     => 'logout',
                                'roles' => array(
                                    Roles::$TA
                                ),
                                'title'=>"Logout"
                            ),
                        ),
                    ),

                ),
            ),

        ),
    ),
);