<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Student\Controller\Index' => 'Student\Controller\IndexController',
            'Student\Controller\User' => 'Student\Controller\UserController'
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'student' => array(
                'type' => 'literal',
                'options' => array(
                    'route'    => '/student',
                    'defaults' => array(
                        'controller' => 'Student\Controller\User',
                        'action'     => 'index',
                        'roles' => array(
                            Roles::$STUDENT
                        ),
                        'title'=>"Home"
                    ),

                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'section' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/section/[:sectionID]',
                            'constraints'=>array(
                                "sectionID"=>'[a-zA-Z0-9_-]+',
                            ),
                            'defaults' => array(
                                'controller' => 'Student\Controller\User',
                                'action'     => 'sectionHome',

                                'roles' => array(
                                    Roles::$STUDENT
                                ),
                                'title'=>"Section Home"
                            ),
                        ),
                    ),
                    // Segment route for viewing one blog post
                    'login' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/login',
                            'defaults' => array(
                                'controller' => 'Student\Controller\Index',
                                'action'     => 'login',
                                'roles' => array(
                                    Roles::$GUEST
                                ),
                                'title'=>"Login"
                            ),
                        ),
                    ),
                    'logout' => array(
                        'type' => 'literal',
                        'options' => array(
                            'route' => '/logout',
                            'defaults' => array(
                                'controller' => 'Student\Controller\User',
                                'action'     => 'logout',
                                'roles' => array(
                                    Roles::$STUDENT
                                ),
                                'title'=>"Logout"
                            ),
                        ),
                    ),

                ),
            ),

        ),
    ),
);