<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Application\Roles;

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Assessments\Controller\Index' => 'Assessments\Controller\IndexController',
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(

// Uncomment below to add routes
        'routes' => array(
            "running-assessment"=>array(
                'type' => 'segment',
                'options' => array(
                    'route' => '/active-assessments/[:answeredID]',
                    'constraints'=>array(
                        'answeredID'=>'[0-9]+'
                    ),
                    'defaults' => array(
                        'controller' => 'Assessments\Controller\Index',
                        'action' => 'answeredReport',
                        'roles' => array(
                            Roles::$STUDENT,
                            Roles::$INSTRUCTOR,
                            Roles::$ADMIN
                        ),
                        'title'=>"Assessments Single Report"
                    )
                )
            ),
            "running-assessment-all"=>array(
                'type' => 'segment',
                'options' => array(
                    'route' => '/active-assessments/all',
                    'defaults' => array(
                        'controller' => 'Assessments\Controller\Index',
                        'action' => 'answeredReports',
                        'roles' => array(
                            Roles::$STUDENT,
                            Roles::$INSTRUCTOR,
                            Roles::$ADMIN
                        ),
                        'title'=>"Assessments Single Report"
                    )
                )
            ),
            'assessments' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/assessments',
                    'defaults' => array(
                        'controller' => 'Assessments\Controller\Index',
                        'action' => 'index',
                    )
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    "create"=>array(
                        'type' => 'Literal',
                        'options' => array(
                            'route' => '/create',
                            'defaults' => array(
                                'controller' => 'Assessments\Controller\Index',
                                'action' => 'create',
                                'roles' => array(
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN
                                ),
                                'title'=>"Assessments View"
                            )
                        ),
                        'may_terminate' => true,
                    ),
                    "view"=>array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/[:assessmentID]',
                            'constraints'=>array(
                                'assessmentID'=>'[0-9]+'
                            ),
                            'defaults' => array(
                                'controller' => 'Assessments\Controller\Index',
                                'action' => 'view',
                                'roles' => array(
                                    Roles::$STUDENT,
                                    Roles::$INSTRUCTOR,
                                    Roles::$ADMIN
                                ),
                                'title'=>"Assessments View"
                            )
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(

                            "start"=>array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/start',
                                    'defaults' => array(
                                        'controller' => 'Assessments\Controller\Index',
                                        'action' => 'start',
                                        'roles' => array(
                                            Roles::$STUDENT
                                        ),
                                        'title'=>"Assessments View"
                                    )
                                ),
                            ),
                            "run"=>array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/run',
                                    'defaults' => array(
                                        'controller' => 'Assessments\Controller\Index',
                                        'action' => 'run',
                                        'roles' => array(
                                            Roles::$STUDENT
                                        ),
                                        'title'=>"Assessments run"
                                    )
                                ),
                            ),
                            "submit"=>array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/submit',
                                    'defaults' => array(
                                        'controller' => 'Assessments\Controller\Index',
                                        'action' => 'submit',
                                        'roles' => array(
                                            Roles::$STUDENT
                                        ),
                                        'title'=>"Assessments Submit"
                                    )
                                ),
                            ),
                            "edit"=>array(
                                'type' => 'literal',
                                'options' => array(
                                    'route' => '/edit',
                                    'defaults' => array(
                                        'controller' => 'Assessments\Controller\Index',
                                        'action' => 'edit',
                                        'roles' => array(
                                            Roles::$INSTRUCTOR,
                                            Roles::$ADMIN
                                        ),
                                        'title'=>"Assessments View"
                                    )
                                ),
                                'may_terminate' => true,
                                'child_routes' => array(
                                    "add-question"=>array(
                                        'type' => 'literal',
                                        'options' => array(
                                            'route' => '/add-question',
                                            'defaults' => array(
                                                'controller' => 'Assessments\Controller\Index',
                                                'action' => 'addQuestion',
                                                'roles' => array(
                                                    Roles::$INSTRUCTOR,
                                                    Roles::$ADMIN
                                                ),
                                                'title'=>"Assessments View Add Question"
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        ),
//        'may_terminate' => true,
//        'child_routes' => array(
//            'default' => array(
//                'type' => 'Segment',
//                'options' => array(
//                    'route' => '/[:controller[/:action]]',
//                    'constraints' => array(
//                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
//                    )
//                )
//            )
//        )
    )
);