<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/9/2017
 * Time: 7:08 AM
 */
use Application\Model\Question;

/** @var \Application\Model\Question[] $Questions */
$Questions=$this->Questions;

echo "<table class='table'>".
    "   <thead>".
    "      <tr>".
    "         <th>Question</th>".
    "         <th>Owner</th>".
    "      </tr>".
    "   </thead>".
    "   <tbody>";

/** @var Question $question */
foreach($Questions as $question){
    echo "      <tr question-id='$this->$question->getQuestionID()' onclick='eventManager.trigger(\"questions\",\"selection\",\"selected\"".'{questionID:$(this).attr("question-id");}'.">".
        "          <td>".$question->getQuestion()."</td>".
        "          <td>".$question->getCreatedBy()->getUserName()."</td>".
        "      </tr>";

}
echo "</tbody>";
echo "</table>";