<?php
/**
 * Created by PhpStorm.
 * User: Hector
 * Date: 3/8/2017
 * Time: 7:21 PM
 */

/** @var \Application\Model\CourseContent $CourseContentItem */
$CourseContentItem=$this->CourseContentItem;
$BaseURL=$this->BaseURL;
$fileURL="$BaseURL/course-content/{$CourseContentItem->getContentID()}/run";
?>
<div class="col-lg-12">
    <b>If this item does not open automatically you can <a target="_blank" href='<?php echo $fileURL ?>'>open <?php echo $CourseContentItem->getName() ?></a></b>
</div>
<div class="col-lg-12">

    <?php if($CourseContentItem->getProperties()["File"]["Type"]=='application/pdf'){ ?>
    <embed scale="tofit" name="PDFEmbeded" alt height="869" id="PDFEmbededID" src="<?php echo $fileURL  ?>" type="application/pdf" controller="true" width="100%" title="<?php echo $CourseContentItem->getName()  ?>"/>

    <?php } else if($CourseContentItem->getProperties()["File"]["Type"]=='text/html'){ ?>
    <?php echo file_get_contents($CourseContentItem->getProperties()["File"]["Path"]); ?>

    <?php } else if($CourseContentItem->getProperties()["File"]["Type"]=='text/text'){ ?>
    <?php echo file_get_contents($CourseContentItem->getProperties()["File"]["Path"]); ?>

    <?php } else if($CourseContentItem->getProperties()["File"]["Type"]=='image/png'){ ?>
        <img src="<?php echo $fileURL  ?>" style="max-width:100%">

    <?php } else if($CourseContentItem->getProperties()["File"]["Type"]=='image/jpeg'){ ?>
        <img src="<?php echo $fileURL  ?>" style="max-width:100%">

    <?php } else if($CourseContentItem->getProperties()["File"]["Type"]=='video'){ ?>
    <video width="320" height="240" controls>
        <source src="<?php echo $fileURL?>" type="video/mp4">
        Your Browser Does not Support the video tag.
    </video>

    <?php } else{ ?>
        <span class='label label-success'><?php echo $CourseContentItem->getProperties()["File"]["Type"] ?></span>
        <a href='<?php echo $fileURL ?>' class="btn btn-lg">Clear Here To Download</a>
    <?php }  ?>
</div>

