<!--<style>-->
<!--    nav {-->
<!--        line-height:30px;-->
<!--        background-color: #1f88ee;-->
<!--        height:180px;-->
<!--        width:200px;-->
<!--        float:left;-->
<!--        padding:10px;-->
<!--    }-->
<!--</style>-->
<?php
$this->headTitle($this->translate('ELMHouston - Home'));
?>

<div class="col-lg-12">
    <h1 class="display-1">Welcome to CELO - Login page</h1>
</div>
<div class="col-lg-12">
    <div class="col-lg-4"></div>
    <a href="/login" class="btn btn-black btn-primary">Main Login</a>
    <div class="col-lg-4"></div>
</div>